image:
  name: mongo
  tag: 4.2

healthCheck:
  paymentDb:
    readinessProbe:
      timeoutSeconds: 5
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 5
    livenessProbe:
      timeoutSeconds: 5
      initialDelaySeconds: 180
      failureThreshold: 5
      periodSeconds: 5
